always_on_top: true
big_joker_shown: ğŸƒ
detect_interval_sec: 0.2
device_choice: cuda
debug_mode: false
frame_length: 3
little_joker_shown: ğŸƒŸ
reset_time: 3.0
show_played_cards: true
window_layouts:
  JJæ–—åœ°ä¸»(å«æ§ä»¶):
    layout:
      landlord_cards:
      - 0.35
      - 0.08
      - 0.45
      - 0.15
      opponent_left:
      - 0.2
      - 0.32
      - 0.455
      - 0.49
      opponent_right:
      - 0.46
      - 0.32
      - 0.8
      - 0.49
      player_hand:
      - 0.04
      - 0.7
      - 0.96
      - 0.85
      player_played:
      - 0.04
      - 0.5
      - 0.96
      - 0.6
    window_title: JJæ–—åœ°ä¸»
  JJæ–—åœ°ä¸»(å…¨å±):
    layout:
      landlord_cards:
      - 0.37
      - 0
      - 0.55
      - 0.08
      opponent_left:
      - 0.2
      - 0.25
      - 0.47
      - 0.45
      opponent_right:
      - 0.48
      - 0.25
      - 0.85
      - 0.45
      player_hand:
      - 0.04
      - 0.7
      - 0.96
      - 0.85
      player_played:
      - 0.04
      - 0.46
      - 0.96
      - 0.57
    window_title: JJæ–—åœ°ä¸»
yolo_confidence_threshold: 0.6
yolo_iou_threshold: 0.45
yolo_to_card_mapping:
  A: A
  J: J
  JOKER: JOK
  K: K
  Q: Q
  eight: '8'
  five: '5'
  four: '4'
  joker: jok
  nine: '9'
  seven: '7'
  six: '6'
  ten: '10'
  three: '3'
  two: '2'
